### ISSUE TITLE
14 months old version of PyMISP included

### ISSUE THREAD

**Issue by iglocska** [melicertes/csp#10]
Even if it's unused (as I hope it is), please don't directly include outdated versions of PyMISP. We generally recommend to submodule other projects found on github.

For more information on how submodules work:
https://git-scm.com/docs/git-submodule

**Comment by thanosa75** [comment]
Hi @iglocska - we are now in the process of repackaging the MiSP module. Can you propose the build that is stable as of today so we can consider in our testing the module?

**Comment by iglocska** [comment]
The best is to either just use the HEAD from github, or the current latest release. We have just released a new version today:

https://github.com/MISP/MISP/releases

Hope this helps!

**Comment by thanosa75** [comment]
To be fair, we would appreciate if the release model moves to a LTS or similar approach; otherwise module updates will be (very?) frequent. In addition, if you may, we would like to discuss further modularisation of the concept of MiSP docker containers; we believe we can help (re: https://github.com/MISP/misp-docker)

**Comment by adulau** [comment]
I would prefer that the CSP framework is handling the updates automatically, you can use the tags but the current state of having "old software" in a repository is obviously something that should be avoided.

**Comment by iglocska** [comment]
Moving to a different release cycle is absolutely out of the question. Updating misp is simple and convenient, with API compatibility being maintained by us. Instead of focusing efforts on how to make the contained projects more stale, I'd be much happier to discuss how to automate the update procedure.

Please have a look at the other docker installations (by Harvard security and by DCSO) if you wish to use not modular docker setups.

**Comment by thanosa75** [comment]
We are now working on 2.4.107 release of MiSP - FAT next week.
