### ISSUE TITLE
[Installation manual] Howto register for a CSP installation

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#12]
1.2. You registered for a CSP installation to the central CSP authority

**Comment by thanosa75** [comment]
The various items in the installation manual checklist are part of the process of adding a MELICERTES CSP Node to the production systems. You should apply for this, either by directly contacting the relevant authority or via an application form (TBD not ready yet)

**Comment by rommelfs** [comment]
We're even hosting a MELiCERTES training next week, but haven't seen a possibility to apply for registration yet. Any input would be appreciated.

**Comment by wagner-certat** [comment]
I already reported the missing contact points (spoiler: the helpdesk!) several times in winter already.

Same problem as in #14

**Comment by rommelfs** [comment]
I request to re-open this issue.

**Comment by thanosa75** [comment]
Please clarify why issue is to be reopened. Afaik the issues section of this repository is focused on code. Is there something on code that needs to be addressed re this issue?

**Comment by rommelfs** [comment]
I don't think you can separate documentation and code. If the documentation is incomplete or incorrect, why not improving or fixing it? Currently, the documentation in order to run a CSP installation is not helping, because the prerequisites cannot be met. An installation is be definition not possible.

**Comment by iglocska** [comment]
> Please clarify why issue is to be reopened. Afaik the issues section of this repository is focused on code. Is there something on code that needs to be addressed re this issue?

I think the point is that in order to evaluate the code portions of the repository, users need to be able to install the application. It might seem tempting to maintain a state where installation is difficult enough to discourage users - after all we'd all end up with no github issues for good - however, that's more of a "smell" of users not managing to get the software running than of a flawless code-base :)
