### ISSUE TITLE
[Installation manual] IP address binding

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#14]
1.2.b. Where to send the IP (which?) address to?

**Comment by thanosa75** [comment]
The various items in the installation manual checklist are part of the process of adding a MELICERTES CSP Node to the production systems. Part of the registration/installation is a binding of your CSP node IP address to the trusted list of IP addresses that participate in the system. You need a IPv4 address for this and it will be communicated to all other parties that are interested to contact your team at any point.
