### ISSUE TITLE
Is there an exposed REST API?

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#19]
Many services are connected to the CSP through REST API.
Is the CSP also exposing a REST API?

**Comment by iglocska** [comment]
Some questions and the preliminary answers we've gotten.

- CSP rest APIs are exposed
  - are these APIs allowing users of other CERTs to query? Answer is yes
  - are these APIs working as an overlay over the native app APIs? answer is yes
  - how is ACL handled with a single MISP API key?

**Comment by iglocska** [comment]
During the training we were told that the APIs of CSP act as an overlay over the APIs of the contained applications and that other CSP nodes can trigger requests via these APIs. We wanted clarification on the exact scope of said queries.

**Comment by thanosa75** [comment]
Hi
this is probably a misunderstanding of sorts. The only (published) APIs are the ones in the relevant documentation folder. The CSP-to-CSP layer is the Integration Layer (part of Shared Services component) and it only communicates _known_ types of information (e.g incident, threat, etc) to other parties, as dictated by the relevant trust circles for the given sharing policy. 

CSP itself (via the relevant adapters) can trigger the creation of an object in a local application, as part of the previous interaction. To illustrate, image an incident created on CSP A with trust circle propagation to CSP B, this will cause the following path to be created:

MiSP(A) -> adapter(A) -> IL(A) -> { [ES(A)] } ==> { [IL(B)] and [ES(B) } -> adapter(B) -> MiSP(B)

In no case someone external can reach the 'adapter (B)' directly, only via the relevant IL.
IL transparently also pushes the information to Elastic, for indexing purposes. No external CSP (or other entity) can directly call (or indirectly via IL) an internal application unless explicitly exposed. There is a change request active for exposure of MiSP so MiSP to MiSP direct communication and shared is possible.
