### ISSUE TITLE
Investigation of incident not shared

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#25]
Is this on purpose? Or has it been forgotten to add a sharing policy field to ticket type investigation?

**Comment by intrasoft-rmalik** [comment]
@rommelfs can you provide more context?

**Comment by rommelfs** [comment]
The workflow in RT is:

1. incoming mail is a generating a ticket
2. you decide this is an incident
3. you carry out 1 to n investigations

Incident tickets have a field sharing policy. Investigations don't have it.

Therefore incidents can be shared, but investigations can't.

Is there a reason for this?

**Comment by wagner-certat** [comment]
Are incidents synced in the meantime? In march an incident was only synchronized on creation, not on changes (comments, any communication, linking etc). So keeping other up-to-date was not possible at all.

**Comment by rommelfs** [comment]
see #31

**Comment by intrasoft-rmalik** [comment]
resolved in v4.2.1
