### ISSUE TITLE
ntpd not started in cspvm by default

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#35]
Time will drift easily on VM installation

**Comment by thanosa75** [comment]
Alpine uses `chrony` (https://chrony.tuxfamily.org) for the NTP service. Please confirm that you do not see this process running, by doing:

`ps -ef |grep chronyd`

Thanks

**Comment by rommelfs** [comment]
I confirm I see this process.

I also confirm a time drift of 9 days.

I was able to fix it by starting /etc/init.d/ntpd

**Comment by thanosa75** [comment]
Hi,

starting ntpd will make a mess, you cannot have two ntp clients running at the same time!

I suggest you stop ntpd (provided by busybox) and restart chronyd to see whether it has trouble connecting to it's configured services as noted by the configuration at /etc/chrony/chrony.conf

Best regards,

Thanos

**Comment by thanosa75** [comment]
To further troubleshoot your VM with chrony you could use (I assume ntpd will be stopped and chronyd restarted):

`chronyc activity`

we get:
```200 OK
4 sources online
0 sources offline
0 sources doing burst (return to online)
0 sources doing burst (return to offline)
0 sources with unknown address
```


`chronyc sourcestats`

```210 Number of sources = 4
Name/IP Address            NP  NR  Span  Frequency  Freq Skew  Offset  Std Dev
==============================================================================
router-vzb.servme.network   7   4   34m     -0.011      0.039   -221us  9172ns
ntp-ext.cosng.net           7   5  103m     +0.115      0.238   +751us   225us
ntp1.kolatelecom.ru        20  13  141m     +1.708      0.322  +9682us   870us
mail.fangfufu.co.uk         6   3   43m     -0.006      0.221   -191us    59us
```

**Comment by thanosa75** [comment]
Hello @rommelfs any news?

**Comment by rommelfs** [comment]
What news do you expect? chronyc is running, ntpd is running, still time drifts.
I will only be worried about this once this instance is registered at the central node (which hasn't happened within the last two weeks). So this is for your information if you like to dig into it. If not, fine for me.

**Comment by thanosa75** [comment]
Hello @rommelfs 

Please do the following:
a) stop ntpd and reboot the instance.
b) execute the following: `cronyc sourcestats`, `chronyc activity` and provide us with the output.


Thanks

**Comment by thanosa75** [comment]
Closed as no response received
