### ISSUE TITLE
csp-apache: first-time script refers to missing docker image

### ISSUE THREAD

**Issue by thanosa75** [melicertes/csp#39]
c.i.c.c.c.s.ExternalProcessService       : Unable to find image 'frolvlad/alpine-oraclejdk8:slim' locally
c.i.c.c.c.s.ExternalProcessService       : docker: Error response from daemon: pull access denied for frolvlad/alpine-oraclejdk8, repository does not exist or may require 'docker login'.
c.i.c.c.c.s.ExternalProcessService       : See 'docker run --help'.

in file: `first-time.sh`
line: `docker run -d --rm -v SSLDatavolume:/ssl_data frolvlad/alpine-oraclejdk8:slim sh -c "mkdir -p /ssl_data/crl"`

**Comment by rommelfs** [comment]
Thank you  for the follow-up. This helped to resolve this specific problem.
