### ISSUE TITLE
Potential misinterpretation due to control characters

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#40]
There is probably an interpretation problem in the web interface with the control code output on the shell which colorizes the word 'done'. It shows the output as error.

![Screenshot 2019-07-16 at 09 19 04](https://user-images.githubusercontent.com/274748/61274023-272cbb80-a7ab-11e9-9949-dc519272288f.png)
<img width="634" alt="Screenshot 2019-07-16 at 09 18 52" src="https://user-images.githubusercontent.com/274748/61274033-2c8a0600-a7ab-11e9-8bb7-cec67089f034.png">

**Comment by thanosa75** [comment]
Hi

this is actually due to the output of docker-compose being on stderr rather than stdin. The interpreting logging service attributes ERROR to the stderr by default. 

The 'done' is coloured green due to the ASCII control character ESC[32m but this is irrelevant to the ERROR attribution

**Comment by rommelfs** [comment]
Cool thanks for fixing it.
