### ISSUE TITLE
ContactDB module and associated code

### ISSUE THREAD

**Issue by adulau** [melicertes/csp#41]
While looking at the [overview diagram](https://raw.githubusercontent.com/melicertes/csp/develop/Architecture/CSP_Solution_Architecture_4.0.png), I see there is a ContactDB module. 

Can you point me in the repository where the code for ContactDB is? In the documentation, I see some references to contact management but I'm sure if this is the same application/module in MeliCERTes.

Thank you very much

**Comment by eubrin** [comment]
Hi Alexandre,

I assume you refer to the contact management (cm) and trust circle (tc) application, which can be found here https://github.com/melicertes/csp/tree/master/csp-apps/tc/tc

Cheers,
    - Eugene

**Comment by adulau** [comment]
Cool. Thanks a lot. So the CM/TC are the ContactDB mentioned in the diagram.
