### ISSUE TITLE
After installation: apache is not serving :443

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#43]
Status after successful install with successful startup of all services.

cspvm [/etc]# docker stats --all --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}" --no-stream | sort
NAME                  CPU %               MEM USAGE / LIMIT
csp-activemq          0.10%               96.46MiB / 11.63GiB
csp-anon              0.15%               175.2MiB / 11.63GiB
csp-apache            0.00%               0B / 0B
csp-apache-crl        0.00%               3.5MiB / 11.63GiB
csp-es                1.42%               4.661GiB / 11.63GiB
csp-filebeat          0.03%               5.969MiB / 11.63GiB
csp-il                0.24%               159.1MiB / 11.63GiB
csp-imq               0.00%               0B / 0B
csp-intelmq_adapter   0.09%               305.6MiB / 11.63GiB
csp-jitsi             0.36%               343.7MiB / 11.63GiB
csp-kibana            0.56%               76.54MiB / 11.63GiB
csp-kibana_logs       0.59%               72.45MiB / 11.63GiB
csp-logstash          7.41%               551.8MiB / 11.63GiB
csp-misp              0.20%               21.3MiB / 11.63GiB
csp-misp-filebeat     0.04%               2.969MiB / 11.63GiB
csp-misp-logstash     7.13%               489.1MiB / 11.63GiB
csp-misp_adapter      0.11%               3.121MiB / 11.63GiB
csp-mock              0.00%               6.703MiB / 11.63GiB
csp-mysql             0.07%               36.43MiB / 11.63GiB
csp-oam               0.38%               702.3MiB / 11.63GiB
csp-oam-filebeat      0.08%               4.727MiB / 11.63GiB
csp-oam-logstash      7.13%               548.5MiB / 11.63GiB
csp-oc                0.00%               40.29MiB / 11.63GiB
csp-ocdb              0.07%               39.64MiB / 11.63GiB
csp-ocredis           0.08%               5.023MiB / 11.63GiB
csp-postgres          0.74%               7.508MiB / 11.63GiB
csp-redis             0.08%               2.461MiB / 11.63GiB
csp-regrep            0.07%               378MiB / 11.63GiB
csp-rt                0.01%               156.7MiB / 11.63GiB
csp-rt_adapter        0.21%               123.4MiB / 11.63GiB
csp-tc                0.03%               15.14MiB / 11.63GiB
csp-tc-dsl            0.02%               3.32MiB / 11.63GiB
csp-vcb_admin         0.14%               459MiB / 11.63GiB
csp-vcb_teleconf      0.19%               447.4MiB / 11.63GiB
csp-viper             0.33%               4.082MiB / 11.63GiB

netstat -napt
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2533/sshd
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      3180/docker-proxy
tcp        0      0 127.0.0.1:18080         0.0.0.0:*               LISTEN      2852/java
tcp        0      0 :::8083                 :::*                    LISTEN      17902/docker-proxy
tcp        0      0 :::4243                 :::*                    LISTEN      2209/dockerd
tcp        0      0 :::22                   :::*                    LISTEN      2533/sshd
tcp        0      0 :::4443                 :::*                    LISTEN      16536/docker-proxy
tcp        0      0 :::32768                :::*                    LISTEN      3327/docker-proxy
tcp        0      0 :::32770                :::*                    LISTEN      15301/docker-proxy

**Comment by thanosa75** [comment]
As discussed separately, apache will not start if private key has been assigned a passphrase, in contradiction with instructions in the installation guide.
