### ISSUE TITLE
SMTP settings are mandatory but not marked as such

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#44]
In contrast to page 23 of the installation manual, the SMTP settings are not required/mandatory, but should be. 
"""
This form is protected against incomplete submission. A warning will be displayed if the Save button is clicked without completing all the required fields.
"""

The SMTP settings are mandatory for successful installation/startup of the services.

This should be made mandatory in the config wizard.

**Comment by intrasoft-rmalik** [comment]
Interesting point, as the videoconferencing requires the SMTP settings as stated on page 25 of the installation manual. However, if anyone does not want to enable the videoconferencing then they will be forced to enter the SMTP info regardless.

@thanosa75 any thoughts?

**Comment by thanosa75** [comment]
@intrasoft-rmalik the SMTP settings are not required to register CSP and start the installation. If however you use the "Edit SMTP settings" page, to edit them, you will need to fill out the mandatory fields for "Save" button to work. You may as well "Cancel" out of the form though.
