### ISSUE TITLE
Timezone needs to be adjusted in videoconf administration

### ISSUE THREAD

**Issue by thanosa75** [melicertes/csp#47]
The videoconf admin application has time by default to Europe/Athens. It can be confusing for CSPs in other timezones.

**Comment by thanosa75** [comment]
*Workaround*
Edit the local 'docker-compose.yml' file, looking for lines that contain "command:"

Edit the line, adding the following *before* the `-jar` option, such as:

Previous line:
`command: java -Xmx512m -Dspring.profiles.active=docker -jar server.jar`

Corrected line (for CET timezone):
`command: java -Xmx512m -Devent.show.timezone.default=CET -Dspring.profiles.active=docker -jar server.jar`

Notes:
1. yml files have spaces for separators, DO NOT modify the spaces before "command".
2. the "command" line is a single line not multi even if it appears as such here.
3. a list of timezones (for java 6 onwards) is provided [here](https://garygregory.wordpress.com/2013/06/18/what-are-the-java-timezone-ids/).

**Comment by wagner-certat** [comment]
> _Workaround_
> Edit the local 'docker-compose.yml' file, looking for lines that contain "command:"

Which one?

Any other steps needed afterwards?

**Comment by thanosa75** [comment]
Clarification added.

**Comment by wagner-certat** [comment]
> Edit the line, adding the following _before_ the `-jar` option, such as:

The line in the vcb-admin or vcb-teleconf section?

**Comment by thanosa75** [comment]
Hello, 

Sorry for not being clear. Both should be modified.

**Comment by wagner-certat** [comment]
I have set it to "Europe/Vienna" now. But the UI shows "CET", not "CEST".

**Comment by thanosa75** [comment]
Hi,

changing it in our debug system, correctly indicates Europe/Vienna. Have you restarted?

![image](https://user-images.githubusercontent.com/1307607/62045470-139f3d00-b20e-11e9-8055-9831d48b42e0.png)

**Comment by wagner-certat** [comment]
I have found the issue in the docker-compose.yml file. Works now
