### ISSUE TITLE
Impossible to use the mobile app to join a Jitsi session

### ISSUE THREAD

**Issue by Rafiot** [melicertes/csp#58]
Not being able to use the mobile app to join a Jitsi session greatly reduce the probability of using of CSP in a realistic way when managing an incident.

The public interface of Jitsi allows to share a unique token to participants, and that token can be used in the mobile app.
CSP should propose a similar functionality in order to be relevant in that context.

**Comment by thanosa75** [comment]
The Jitsi interface with the VCB also exposes the link itself. Although not visible unless you have logged in, if you do login to the conference, you may take it and pass it along (e.g. via slack or other means).

**Comment by Rafiot** [comment]
Ok, thank you for the update on that. I'll give it a try next time we have a conf call over CSP.
