### ISSUE TITLE
Feature request: Collecting log files through web interface

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#74]
It should be technically feasible to collect the constantly required log files you need for debugging through the web interface. It would save the admins of the installations a lot of time collecting, copying, packing, sending those to you.

**Comment by thanosa75** [comment]
Indeed. I +1 this feature!

**Comment by thanosa75** [comment]
Commit id b4cf9976e1788a6d536a144c55c01cad269dd200 fixes this issue, script uploaded.
