### ISSUE TITLE
standalone version installation?

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#8]
For testing and standalone installation reasons, where can one download the ova for Melicertes?
Or the installation instructions?

**Comment by thanosa75** [comment]
It is possible, although for full operation the OVA is not enough, you will  need a full CENTRAL installation as well. Are you OK to be contacted directly for details?

**Comment by rommelfs** [comment]
Sure, you can contact me directly.

**Comment by thanosa75** [comment]
Raised internally, you will be contacted hopefully soon. 
Best regards,
Thanos

**Comment by adulau** [comment]
A small question, can we install the software in this repository without requiring to register to a central node?

**Comment by thanosa75** [comment]
No, connectivity to CENTRAL is _only_ required, for the stage of registration, receiving of approved modules and installation. After installation, CSP nodes regularly provide heartbeats to CENTRAL for the purpose of verification of versions installed and general system health. All documented as part of the API (Configuration API, https://github.com/melicertes/csp/blob/develop/Architecture/API/api_configuration_service.yaml#L41)

IMHO, you may cut internet access at that point to central, but connecting to peers (Trust Circle contacts) would require some (limited) internet connectivity. CENTRAL connectivity is mandatory for updates basically. Hope this helps.

**Comment by adulau** [comment]
Thanks for the feedback. To be sure that I understand correctly, so the software cannot be installed without having access to a closed third-party service?

**Comment by thanosa75** [comment]
Hi,

The project role of CENTRAL is currently run by the consortium but it is soon (November '19 if not sooner) to be handed over to the European Agency for Network and Information Security. So it is not going to be a third-party.

Best regards,
Thanos

**Comment by iglocska** [comment]
Excellent, so when will the CENTRAL component be open sourced and made available on GitHub?

**Comment by thanosa75** [comment]
The CENTRAL component is comprised of modules within this repository that are only centrally installed. Code is already available. I understand that this may not be self-evident so we can provide in documentation, which modules _are only_ centrally installed and which are Node installed. Hopefully this clears it up.

**Comment by rommelfs** [comment]
Please re-open the issue until the standalone installer has been made available. Thanks

**Comment by thanosa75** [comment]
Hi @rommelfs, 

The standalone installer is the same installer. We use a docker-compose.yml to bootstrap the central configuration service (client and server,both) which then are used to install modules in the central and subsequently, install central itself. The actual file (https://github.com/melicertes/csp/blob/develop/deployment/docker/central/docker-compose.yml) is in the repo and the process itself is part of the Central Installation manual. The "central.zip" mentioned in the manual is the content of the directory where the docker-compose file is found. 

The process may not be clear ATM but it is straightforward, following the guide. You do need other more vital parts, e.g. a PKI service that are not part of the software but a service in itself though, to be a full central installation.

Hope this helps.

**Comment by rommelfs** [comment]
Could you be specific and tell me how to install the software? I want to use it tomorrow during the training. 

Ideally, without the need to use docker or any other container technology.

**Comment by intrasoft-rmalik** [comment]
@rommelfs can we close this issue?

**Comment by rommelfs** [comment]
As far as I can tell no information has been provided how to install and run in standalone mode. I wouldn't recommend closing the issue.

**Comment by rommelfs** [comment]
As discussed during the handover, the installation guide has since been included in the installation manual.
