### ISSUE TITLE
14 months old version of MISP included

### ISSUE THREAD

**Issue by iglocska** [melicertes/csp#9]
Even if it's unused (as I hope it is), please don't directly include outdated versions of MISP. We generally recommend to submodule other projects found on github. 

For more information on how submodules work:
https://git-scm.com/docs/git-submodule

**Comment by thanosa75** [comment]
@iglocska same as in #10 pls indicate which build to base the refresh on.

**Comment by thanosa75** [comment]
We are now working on 2.4.107 release of MiSP - FAT next week.
